<?php
require_once 'config.php';
require_once 'StalkerLite.php';

set_time_limit(120);
error_reporting(E_ALL);
ini_set('display_errors', 0);

$serverId = $_GET['server'] ?? '';
$server = getStalkerServerById($serverId);
if (!$server) {
    http_response_code(400);
    die("# ERROR: Invalid server ID\n");
}

$url   = $server['url'];
$mac   = $server['mac'];
$model = $_GET['model'] ?? '';  // empty = auto-detect

// Advanced optional params
$extras = [];
if (!empty($_GET['sn_cut']))     $extras['sn_cut'] = $_GET['sn_cut'];
if (!empty($_GET['device_id']))  $extras['device_id'] = $_GET['device_id'];
if (!empty($_GET['device_id2'])) $extras['device_id2'] = $_GET['device_id2'];
if (!empty($_GET['signature']))  $extras['signature'] = $_GET['signature'];

$proxyMode = $_GET['proxy'] ?? 'redirect';

// --- Auto-detect model if not provided ---
if (empty($model)) {
    // Extended list: newer models first, then classic ones for backward compatibility
    $commonModels = [
        // Newest MAG models (optimised for Ministra 5.x / Stalker 5.x)
        'MAG524', 'MAG544w3', 'MAG500A', 'MAG520', 'MAG522', 'MAG528', 'MAG540',
        // Classic models (fallback for older portals)
        'MAG250', 'MAG254', 'MAG256', 'MAG322', 'MAG324', 'MAG349', 'MAG351', 'MAG420', 'MAG424'
    ];
    $detectedModel = null;
    foreach ($commonModels as $testModel) {
        $testStalker = new StalkerLite($url, $mac, $testModel, $extras);
        $testConnect = $testStalker->connect();
        if ($testConnect['success']) {
            $detectedModel = $testModel;
            break;
        }
    }
    if (!$detectedModel) {
        http_response_code(503);
        die("# ERROR: Could not auto-detect MAG model. Please specify one manually in advanced options.\n");
    }
    $model = $detectedModel;
}

// Now use the detected or user-specified model
$stalker = new StalkerLite($url, $mac, $model, $extras);
$connect = $stalker->connect();
if (!$connect['success']) {
    http_response_code(503);
    die("# ERROR: Handshake failed – " . ($connect['error'] ?? 'unknown') . "\n");
}

$channels = $stalker->getChannels();
if (empty($channels)) {
    http_response_code(503);
    die("# ERROR: No channels found\n");
}

// Build self URL for stream resolver
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
$host = $_SERVER['HTTP_HOST'];
$self = $protocol . $host . rtrim(dirname($_SERVER['SCRIPT_NAME']), '/') . '/play.php';

// Forward all relevant params to play.php
$forwardParams = [];
$forwardParams['model'] = $model;
foreach (['sn_cut', 'device_id', 'device_id2', 'signature'] as $p) {
    if (!empty($_GET[$p])) $forwardParams[$p] = $_GET[$p];
}
$forwardParams['proxy'] = $proxyMode;
$forwardQuery = http_build_query($forwardParams);

// Output M3U
header('Content-Type: audio/x-mpegurl');
header('Content-Disposition: inline; filename="' . preg_replace('/[^a-z0-9]/i', '_', $server['name']) . '.m3u"');
header("Cache-Control: no-store, no-cache, must-revalidate");

echo "#EXTM3U\n";
echo "# Playlist generated by Demonji Stalker Manager\n";
echo "# Server: " . $server['name'] . "\n";
echo "# Detected/Used model: " . $model . "\n";
echo "# Proxy mode: " . $proxyMode . "\n";
echo "# Channels: " . count($channels) . "\n\n";

foreach ($channels as $ch) {
    $id   = $ch['id'];
    $name = $ch['name'];
    $logo = $ch['logo'];
    $group= $ch['genre_name'] ?? 'General';
    $streamUrl = $self . '?server=' . urlencode($serverId) . '&id=' . urlencode($id);
    if ($forwardQuery) $streamUrl .= '&' . $forwardQuery;
    
    echo '#EXTINF:-1 tvg-id="' . htmlspecialchars($id) . '" tvg-name="' . htmlspecialchars($name) . '" tvg-logo="' . htmlspecialchars($logo) . '" group-title="' . htmlspecialchars($group) . '",' . $name . "\n";
    echo $streamUrl . "\n";
}
?>
