<?php
require_once 'config.php';
require_once 'StalkerLite.php';

set_time_limit(120);
error_reporting(E_ALL);
ini_set('display_errors', 0); // Don't leak errors into M3U

$serverId = $_GET['server'] ?? '';
$server = getStalkerServerById($serverId);
if (!$server) {
    http_response_code(400);
    die("# ERROR: Invalid server ID\n");
}

$url   = $server['url'];
$mac   = $server['mac'];
$model = $server['model'] ?? 'MAG250';

// Handshake and get channels
$stalker = new StalkerLite($url, $mac, $model);
$connect = $stalker->connect();
if (!$connect['success']) {
    http_response_code(503);
    die("# ERROR: Handshake failed – " . ($connect['error'] ?? 'unknown') . "\n");
}

$channels = $stalker->getChannels();
if (empty($channels)) {
    http_response_code(503);
    die("# ERROR: No channels found\n");
}

// Build self URL for stream proxy
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
$host = $_SERVER['HTTP_HOST'];
$self = $protocol . $host . rtrim(dirname($_SERVER['SCRIPT_NAME']), '/') . '/play.php';

// Output M3U
header('Content-Type: audio/x-mpegurl');
header('Content-Disposition: inline; filename="' . preg_replace('/[^a-z0-9]/i', '_', $server['name']) . '.m3u"');
header("Cache-Control: no-store, no-cache, must-revalidate");

echo "#EXTM3U\n";
echo "# Playlist generated by Demonji Stalker Manager\n";
echo "# Server: " . $server['name'] . "\n";
echo "# Channels: " . count($channels) . "\n\n";

foreach ($channels as $ch) {
    $id   = $ch['id'];
    $name = $ch['name'];
    $logo = $ch['logo'];
    $group= $ch['genre_name'] ?? 'General';
    $streamUrl = $self . '?server=' . urlencode($serverId) . '&id=' . urlencode($id);
    
    echo '#EXTINF:-1 tvg-id="' . htmlspecialchars($id) . '" tvg-name="' . htmlspecialchars($name) . '" tvg-logo="' . htmlspecialchars($logo) . '" group-title="' . htmlspecialchars($group) . '",' . $name . "\n";
    echo $streamUrl . "\n";
}
?>