<?php
require_once 'config.php';
require_once 'StalkerLite.php';

set_time_limit(120);
error_reporting(E_ALL);
ini_set('display_errors', 0);

$serverId = $_GET['server'] ?? '';
$server = getStalkerServerById($serverId);
if (!$server) {
    http_response_code(400);
    die("# ERROR: Invalid server ID\n");
}

// Base server data
$url   = $server['url'];
$mac   = $server['mac'];
$model = $_GET['model'] ?? $server['model'] ?? 'MAG250';

// Advanced optional params
$extras = [];
if (!empty($_GET['sn_cut']))     $extras['sn_cut'] = $_GET['sn_cut'];
if (!empty($_GET['device_id']))  $extras['device_id'] = $_GET['device_id'];
if (!empty($_GET['device_id2'])) $extras['device_id2'] = $_GET['device_id2'];
if (!empty($_GET['signature']))  $extras['signature'] = $_GET['signature'];

$proxyMode = $_GET['proxy'] ?? 'redirect'; // 'redirect' or 'proxy'

// Handshake and get channels
$stalker = new StalkerLite($url, $mac, $model, $extras);
$connect = $stalker->connect();
if (!$connect['success']) {
    http_response_code(503);
    die("# ERROR: Handshake failed – " . ($connect['error'] ?? 'unknown') . "\n");
}

$channels = $stalker->getChannels();
if (empty($channels)) {
    http_response_code(503);
    die("# ERROR: No channels found\n");
}

// Build self URL for stream resolver
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
$host = $_SERVER['HTTP_HOST'];
$self = $protocol . $host . rtrim(dirname($_SERVER['SCRIPT_NAME']), '/') . '/play.php';

// Prepare query params to forward to play.php
$forwardParams = [];
if ($model !== ($server['model'] ?? 'MAG250')) $forwardParams['model'] = $model;
foreach (['sn_cut', 'device_id', 'device_id2', 'signature'] as $p) {
    if (!empty($_GET[$p])) $forwardParams[$p] = $_GET[$p];
}
$forwardParams['proxy'] = $proxyMode;
$forwardQuery = http_build_query($forwardParams);

// Output M3U
header('Content-Type: audio/x-mpegurl');
header('Content-Disposition: inline; filename="' . preg_replace('/[^a-z0-9]/i', '_', $server['name']) . '.m3u"');
header("Cache-Control: no-store, no-cache, must-revalidate");

echo "#EXTM3U\n";
echo "# Playlist generated by Demonji Stalker Manager\n";
echo "# Server: " . $server['name'] . "\n";
echo "# Proxy mode: " . $proxyMode . "\n";
echo "# Channels: " . count($channels) . "\n\n";

foreach ($channels as $ch) {
    $id   = $ch['id'];
    $name = $ch['name'];
    $logo = $ch['logo'];
    $group= $ch['genre_name'] ?? 'General';
    // Append all advanced params to the stream URL
    $streamUrl = $self . '?server=' . urlencode($serverId) . '&id=' . urlencode($id);
    if ($forwardQuery) $streamUrl .= '&' . $forwardQuery;
    
    echo '#EXTINF:-1 tvg-id="' . htmlspecialchars($id) . '" tvg-name="' . htmlspecialchars($name) . '" tvg-logo="' . htmlspecialchars($logo) . '" group-title="' . htmlspecialchars($group) . '",' . $name . "\n";
    echo $streamUrl . "\n";
}
?>
